// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProsumerInfo.Models;

namespace ProsumerInfo.Migrations
{
    [DbContext(typeof(ProsumerDbContext))]
    [Migration("20181211163706_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProsumerInfo.Models.Prosumer", b =>
                {
                    b.Property<int>("ProsumerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InstallationsID");

                    b.Property<int>("KWhBlocksTotalConsumed");

                    b.Property<int>("KWhBlocksTotalProduction");

                    b.Property<int>("ProsumerCurrencyNowInBlocks");

                    b.Property<DateTime>("ProsumerLastUpdated");

                    b.Property<DateTime>("kWhBlocksLastMeterStamp");

                    b.HasKey("ProsumerID");

                    b.ToTable("Prosumers");
                });

            modelBuilder.Entity("ProsumerInfo.Models.ProsumerSmartMeterRecordsLog", b =>
                {
                    b.Property<int>("ProsumerSmartMeterRecordsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InstallationsID");

                    b.Property<int>("KWhBlocksConsumed");

                    b.Property<int>("KWhBlocksProduced");

                    b.Property<int>("ProsumerID");

                    b.HasKey("ProsumerSmartMeterRecordsID");

                    b.HasIndex("ProsumerID");

                    b.ToTable("ProsumerSmartMeterRecordsLogs");
                });

            modelBuilder.Entity("ProsumerInfo.Models.ProsumerSmartMeterRecordsLog", b =>
                {
                    b.HasOne("ProsumerInfo.Models.Prosumer", "Prosumer")
                        .WithMany()
                        .HasForeignKey("ProsumerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
