// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prosumer.Models;

namespace Prosumer.Migrations
{
    [DbContext(typeof(ProsumerDBContext))]
    partial class ProsumerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prosumer.Models.Prosumer", b =>
                {
                    b.Property<int>("ProsumerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActualComsumed");

                    b.Property<int>("ActualProduced");

                    b.Property<int>("CurrentComsumed");

                    b.Property<int>("CurrentProduced");

                    b.Property<int>("ExpectedComsumed");

                    b.Property<int>("ExpectedProduced");

                    b.Property<string>("Type");

                    b.HasKey("ProsumerID");

                    b.ToTable("Prosumers");
                });
#pragma warning restore 612, 618
        }
    }
}
