@startuml table-domains

!include setup.iuml
_set class_circle
_applysetup







package "Mini Smart Grid Domain Helper Classes" <<Rectangle>> {



    class SmartGridRegistration
    {
        SmartGridRegistrations : List<SmartGrid>
        
    }

    class ProsumerRegistration
    {
        ProsumerRegistration : List<Prosumer>

    }

    class TraderCalculator
    {
        TraderCalculator : List<Trader>
        GetAllSmartGrid

    }
}
@enduml