@startuml ddd-diagram-prosumer-grid

!include setup.iuml
_set class_circle
_applysetup


!define grid (D,#33CCCC) SmartGridInfo
!define prosumer (D,#00FF00) ProsumerInfo
!define trader (D,#0000FF) TraderInfo




package "Village Smart Grid - Domain Driven Design - SmartGrid & Prosumers" <<Rectangle>> {
    class SmartGrid << grid >>
    {
        [ PK ] SmartGridID : int
        SmartGridInfo : string
        SmartGridRegistration : string
        TotalProsumersCount : int

    }

    class SmartGridProsumer << grid >>
    {
        [ Key ] SmartGridProsumersID : int
        SmartGrid : int
        SmartGrid : SmartGrid
        InstallationsID : int
    }

    SmartGridProsumer -up-> SmartGrid

    class Prosumer << prosumer >>
    {
        [ Key ] ProsumerID : int
        InstallationsID : int
        kWhBlocksTotalProduction : int
        kWhBlocksTotalConsumed : int
        kWhBlocksLastMeterStamp : int      
        prosumerCurrencyInBlocks : int
        ProsumerLastUpdated : DateTime
    }

    class ProsumerSmartMeterRecordsLog << prosumer >>
    {
        [ Key ] ProsumerSmartMeterRecordID : int
        ProsumerID : int
        Prosumer : Prosumer
        InstallationsID : int
        kWhBlocksProduced : int
        kWhBlocksConsumed : int
        TimeStamp : DateTime
    }
    ProsumerSmartMeterRecordsLog -up-> Prosumer
}
@enduml