@startuml ddd-diagram-trader

!include setup.iuml
_set class_circle
_applysetup


!define grid (D,#33CCCC) SmartGridInfo
!define prosumer (D,#00FF00) ProsumerInfo
!define trader (D,#0000FF) TraderInfo




package "Village Smart Grid - Domain Driven Design - TraderInfo" <<Rectangle>> {
    class Trader << trader >>
    {
        [ id ] TraderID : string
        PlantProsumekWhBlocks : int
        PlantProsumeFromTime : DateTime
        LastUpdated : DateTime
        completedTrades : CompletedTradesLog[]
        currentTrade : CurrentTrade[]
        plannedTrades : PlannedTrade[]
        prosumerTraderInfo : ProsumerTraderInfo[]
        prosumerTradesOffers : ProsumerTradesOffer[]
        prosumerTradesSales : ProsumerTradesSale[]
    }
    
    class ProsumerTraderInfo << trader >>
    {
        [ id ] ProsumerTraderInfoID : string
        ProsumerID : int
        DailyProfit : double
        AllTimeProfit : double
        SellRate : double
        
    }

    Trader <-right- ProsumerTraderInfo

    class CompletedTradesLog << trader >>
    {
        [ id ] CompletedTradeID : string
        ProsumerBuyerID : int
        ProsumerSellerID : int
        ProsumeTradeFromTime : DateTime
        ProsumeTradeToTime : DateTime
        kWhBlocks : int
        TradeOccuredAt : DateTime
        kWhBlockPrice : double
    }

    Trader <-up- CompletedTradesLog
    
    class CurrentTrade << trader >>
    {
        [ id ] CurrentTradesID : string
        ProsumerBuyerID : int
        ProsumerSellerID : int
        ProsumeTradeFromTime : DateTime
        ProsumeTradeToTime : DateTime
        kWhBlocks : int
        TradeOccuredAt : DateTime
        kWhBlockPrice : double
    }
    Trader <-up- CurrentTrade
    
    class PlannedTrade << trader >>
    {
        [ id ] PlannedTradesID : string
        ProsumerBuyerID : int
        ProsumerSellerID : int
        ProsumeTradeFromTime : DateTime
        ProsumeTradeToTime : DateTime
        kWhBlocks : int
        TradeOccuredAt : DateTime
        kWhBlockPrice : double
    }
    Trader <-up- PlannedTrade
    class ProsumerTradesOffer << trader >>
    {
        [ id ] ProsumerTradesOffersID : string
        ProsumerSellerID : int
        kWhBlocks : int
        kWhBlockPrice : double
    } 
    Trader <-down- ProsumerTradesOffer
    class ProsumerTradesSale << trader >>
    {
        [ id ] ProsumerTradeSalesID : string
        ProsumerSellerID : int
        OfferFromTime : DateTime
        OfferToTime : DateTime
        kWhBlocks : int
        kWhBlockPrice : double
    }  
    Trader <-down- ProsumerTradesSale
}
@enduml