@startuml ddd-diagram-trader

!include setup.iuml
_set class_circle
_applysetup


!define grid (D,#33CCCC) SmartGridInfo
!define prosumer (D,#00FF00) ProsumerInfo
!define trader (D,#0000FF) TraderInfo




package "Village Smart Grid - Domain Driven Design - TraderInfo" <<Rectangle>> {
    class Trader << trader >>
    {
        [ id ] TraderID : int
        PlantProsumekWhBlocks : int
        PlantProsumeFromTime : DateTime
        LastUpdated : DateTime
    }
    
    class ProsumerTraderInfo << trader >>
    {
        ProsumerID : int
        DailyProfit : double
        AllTimeProfit : double
        SellRate : double
        
    }

    class CompletedTradesLog << trader >>
    {
        [ id ] CompletedTradesID : string
        ProsumerBuyerID : int
        ProsumerSellerID : int
        ProsumeTradeFromTime : DateTime
        ProsumeTradeToTime : DateTime
        kWhBlocks : int
        TradeOccuredAt : DateTime
        kWhBlockPrice : double
    }
    
    class CurrentTrades << trader >>
    {
        [ id ] CurrentTradesID : string
        ProsumerBuyerID : int
        ProsumerSellerID : int
        ProsumeTradeFromTime : DateTime
        ProsumeTradeToTime : DateTime
        kWhBlocks : int
        TradeOccuredAt : DateTime
        kWhBlockPrice : double
    }
    
    class PlannedTrades << trader >>
    {
        [ id ] PlannedTradesID : string
        ProsumerBuyerID : int
        ProsumerSellerID : int
        ProsumeTradeFromTime : DateTime
        ProsumeTradeToTime : DateTime
        kWhBlocks : int
        TradeOccuredAt : DateTime
        kWhBlockPrice : double
    }

    class ProsumerTradesOffers << trader >>
    {
        [ id ] ProsumerTradesOffersID : string
        ProsumerSellerID : int
        kWhBlocks : int
        kWhBlockPrice : double
    } 

    class ProsumerTradesSales << trader >>
    {
        [ id ] ProsumerTradeSalesID : string
        ProsumerSellerID : int
        OfferFromTime : DateTime
        OfferToTime : DateTime
        kWhBlocks : int
        kWhBlockPrice : double
    }  
}
@enduml