// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSmartGrid.Models;

namespace MiniSmartGrid.Migrations
{
    [DbContext(typeof(SmartGridDBContext))]
    [Migration("20181211161512_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiniSmartGrid.Models.SmartGrid", b =>
                {
                    b.Property<int>("SmartGridID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConsumerType");

                    b.Property<string>("ProductionType");

                    b.Property<string>("SmartMeter");

                    b.HasKey("SmartGridID");

                    b.ToTable("SmartGrids");
                });
#pragma warning restore 612, 618
        }
    }
}
